### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by justjake** [jdan/cards#2]
- What license is this code released under?
- It'd be nice if it was public domain, MIT, etc.
- and that was recorded in the repo officially.

**Comment by justjake** [comment]
I really like the stylesheet, but I want to convert the site generation stuff to next.js/blitzjs. For now I will refrain from reading the sources.

**Comment by jdan** [comment]
MIT lit df3e126c7dadf2fbd3b330e6f06bd7efda5a66ae
